const DEFAULT_HINT_EN = 'Focus on the key concepts from the official answer.';
const DEFAULT_HINT_HE = 'התמקד במושגים המרכזיים מהתשובה הרשמית.';

export function card(id, category, en, he, opts = {}) {
  return {
    id,
    category,
    question_en: en.q,
    question_he: he.q,
    hint_en: en.hint ?? DEFAULT_HINT_EN,
    hint_he: he.hint ?? DEFAULT_HINT_HE,
    correctAnswer_en: en.a,
    correctAnswer_he: he.a,
    ...(opts.code ? { code_snippet: opts.code } : {}),
  };
}

export default [
  card(1, 'JavaScript / Basics',
    {
      q: 'What is the difference between undefined and null?',
      hint: 'Think about declared-but-unassigned vs intentionally empty.',
      a: 'Undefined means a variable that has not yet been assigned a value. null is an assignment value that can represent no value.',
    },
    {
      q: 'מה ההבדל בין undefined ל-null?',
      hint: 'חשוב על משתנה שהוכרז אך לא הוקצה לו ערך, לעומת השמה מכוונת של "אין ערך".',
      a: 'undefined מייצג משתנה שטרם הוקצה לו ערך (declared but unassigned). null הוא ערך שהוקצה במכוון כדי לייצג היעדר ערך או ריק מכוון.',
    },
    { code: "let pet\n// pet is undefined\npet = null\n// pet is assigned null" },
  ),
  card(2, 'JavaScript / Loops',
    {
      q: "What's the output of the following?\nconst arr = ['a', 'b', 'c']\nfor (let x in arr) { console.log(x) }",
      hint: 'Does for...in iterate values or keys?',
      a: 'The output is 0, 1, 2. A for...in loop iterates over enumerable keys (indices as strings), not the array values.',
    },
    {
      q: "מה הפלט של הקוד הבא?\nconst arr = ['a', 'b', 'c']\nfor (let x in arr) { console.log(x) }",
      hint: 'האם for...in עובר על ערכים או על מפתחות?',
      a: 'הפלט הוא 0, 1, 2. לולאת for...in עוברת על מפתחות enumerable (אינדקסים כמחרוזות), ולא על ערכי המערך.',
    },
    { code: "const arr = ['a', 'b', 'c']\nfor (let x in arr) { console.log(x) }" },
  ),
  card(3, 'JavaScript / Core',
    {
      q: 'What is hoisting?',
      a: 'Hoisting is the default behavior of moving all declarations to the top of the scope before code execution.',
    },
    {
      q: 'מהו hoisting?',
      a: 'hoisting הוא ההתנהגות שבה כל ההכרזות (declarations) מועברות לראש ה-scope לפני הרצת הקוד.',
    },
    { code: "foo()\nfunction foo() {}\nconsole.log('gMax exist but value is undefined:', gMax)\nvar gMax = 10" },
  ),
  card(4, 'JavaScript / Core',
    {
      q: 'What is prototype?',
      a: 'Prototypes are the mechanism by which JavaScript objects inherit their features (properties and methods).',
    },
    {
      q: 'מהו prototype?',
      a: 'prototypes הם המנגנון שבו אובייקטים ב-JavaScript יורשים תכונות (properties) ומתודות.',
    },
    { code: "console.log('String.prototype', String.prototype)" },
  ),
  card(5, 'JavaScript / Advanced',
    {
      q: "Challenge: What's IIFE?",
      a: 'Immediately Invoked Function Expression is an anonymous function that runs as soon as it is defined. Main usages: avoid polluting the global namespace and execute async logic immediately.',
    },
    {
      q: 'אתגר: מהו IIFE?',
      a: 'Immediately Invoked Function Expression הוא פונקציה אנונימית שרצה מיד עם הגדרתה. שימושים עיקריים: מניעת זיהום ה-global namespace והרצת לוגיקה אסינכרונית מיידית.',
    },
    { code: "(function init(greet) {\n  const msg = greet + '!'\n  console.log(msg)\n})('Hi')" },
  ),
  card(6, 'JavaScript / Basics',
    {
      q: 'What is the difference between var and let?',
      a: 'var is function scoped while let is block scoped. let is not hoisted in the same usable way as var.',
    },
    {
      q: 'מה ההבדל בין var ל-let?',
      a: 'var הוא function scoped (תחום פונקציה) בעוד let הוא block scoped (תחום בלוק). let לא עובר hoisting בצורה שמאפשרת שימוש לפני ההכרזה כמו var.',
    },
    { code: "var future = 'nice';\n(function () {\n  if (!future) { var future = 'good' }\n  console.log(future)\n}())" },
  ),
  card(7, 'JavaScript / ES6+',
    {
      q: 'Challenge: Explain Spread and Rest',
      a: 'Spread operators expand an array or object into individual elements. Rest operators condense multiple elements into a single array or object.',
    },
    {
      q: 'אתגר: הסבר Spread ו-Rest',
      a: 'Spread (...מפרק/מפזר) מרחיב מערך או אובייקט לאלמנטים בודדים. Rest (...אוסף/איסוף) מאגד מספר אלמנטים למערך או אובייקט אחד.',
    },
    { code: "const nums = [3, 7, 2]\nconst max = Math.max(...nums)\nfunction sumNums(...nums) {\n  return nums.reduce((acc, num) => acc + num, 0)\n}" },
  ),
  card(8, 'JavaScript / ES6+',
    {
      q: 'Challenge: What is Destructuring?',
      a: 'Destructuring assignment syntax unpacks values from arrays or properties from objects into distinct variables.',
    },
    {
      q: 'אתגר: מהו Destructuring?',
      a: 'תחביר destructuring assignment מפרק ערכים ממערכים או properties מאובייקטים למשתנים נפרדים.',
    },
    { code: "var [a1, , , b1] = f()\nconst { p, q } = info" },
  ),
  card(9, 'JavaScript / Core',
    {
      q: 'What is a closure?',
      a: 'A closure is the combination of a function bundled together with references to its surrounding state (lexical environment).',
    },
    {
      q: 'מהו closure?',
      a: 'closure הוא שילוב של פונקציה יחד עם הפניות לסביבה הלקסיקלית (lexical environment) שבה היא נוצרה.',
    },
    { code: "function flashEl(selector) {\n  var el = document.querySelector(selector)\n  setTimeout(function () { el.hidden = false }, 1000)\n}" },
  ),
  card(10, 'JavaScript / Advanced',
    {
      q: 'Challenge: How to make "private" variables?',
      a: 'Private variables can be created with ES modules, closures, or private (#) fields and methods in classes.',
    },
    {
      q: 'אתגר: איך יוצרים משתנים "פרטיים"?',
      a: 'ניתן ליצור משתנים פרטיים באמצעות ES modules, closures, או שדות ומתודות פרטיים (#) במחלקות.',
    },
    { code: "class MyClass {\n  #privateField = 42\n}\nfunction Box() {\n  var val\n  return { set(v) { val = v }, get() { return val } }\n}" },
  ),
  card(11, 'JavaScript / Core',
    {
      q: "Challenge: What's a typical use case for anonymous functions?",
      a: 'If the function reference is only needed once, an anonymous function is syntactically lighter. They are often passed to higher-order functions like Array.map or setTimeout.',
    },
    {
      q: 'אתגר: מהו מקרה שימוש טיפוסי לפונקציות אנונימיות?',
      a: 'אם הפונקציה נדרשת רק פעם אחת, פונקציה אנונימית קלה יותר תחבירית. לעיתים מעבירים אותן לפונקציות מסדר גבוה כמו Array.map או setTimeout.',
    },
    { code: "setTimeout(() => alert('Times up!'), 3000)" },
  ),
  card(12, 'JavaScript / Core',
    {
      q: 'Challenge: arrow functions vs. regular functions',
      a: 'Arrow functions are anonymous, do not have their own arguments keyword, and inherit this from the creation context instead of defining their own.',
    },
    {
      q: 'אתגר: arrow functions לעומת regular functions',
      a: 'arrow functions הן אנונימיות, אין להן keyword arguments משלהן, והן יורשות את this מההקשר שבו נוצרו במקום להגדיר this משלהן.',
    },
    { code: "const person = {\n  fullName: 'Puki',\n  speak(msg) {\n    setTimeout(() => console.log(this.fullName), 1000)\n  }\n}" },
  ),
  card(13, 'JavaScript / Core',
    {
      q: 'Challenge: function foo() {} vs. const foo = function() {}',
      a: 'Function declarations are hoisted and can be called before their definition line. Function expressions assigned to const are not hoisted and cannot be reassigned.',
    },
    {
      q: 'אתגר: function foo() {} לעומת const foo = function() {}',
      a: 'function declarations עוברות hoisting וניתן לקרוא להן לפני שורת ההגדרה. function expressions שהוקצו ל-const לא עוברות hoisting ולא ניתן להקצות אותן מחדש.',
    },
    { code: "function func1() { console.log(arguments) }\nconst func2 = (...args) => console.log(...args)" },
  ),
  card(14, 'JavaScript / Advanced',
    {
      q: 'What is the closure pitfall?',
      a: 'It happens when creating functions inside a loop with var. All callbacks share the same variable reference. Using let solves this because each iteration gets its own binding.',
    },
    {
      q: 'מהו מלכודת ה-closure?',
      a: 'זה קורה כשיוצרים פונקציות בתוך לולאה עם var — כל ה-callbacks חולקים את אותה הפניה למשתנה. שימוש ב-let פותר זאת כי לכל איטרציה יש binding משלה.',
    },
    { code: "var obj = { japan: 61, india: 76 }\nfor (var k in obj) {\n  setTimeout(() => console.log(k, obj[k]), 100)\n}" },
  ),
  card(15, 'JavaScript / Advanced',
    {
      q: 'Another example for closure pitfall',
      a: 'An IIFE can capture the loop index per iteration and return the callback, ensuring each handler gets the correct value.',
    },
    {
      q: 'דוגמה נוספת למלכודת closure',
      a: 'IIFE יכול ללכוד את אינדקס הלולאה בכל איטרציה ולהחזיר את ה-callback, כך שכל handler מקבל את הערך הנכון.',
    },
    { code: "for (var i = 0; i < 3; i++) {\n  link.onclick = (function (num) {\n    return function () { alert(num) }\n  })(i)\n}" },
  ),
  card(16, 'JavaScript / Core',
    {
      q: "Challenge: What's the difference between .call and .apply?",
      a: 'Both come from Function.prototype, set this as the first argument, and execute the function. call passes extra arguments individually; apply passes them as an array. With spread, apply is less common today.',
    },
    {
      q: 'אתגר: מה ההבדל בין .call ל-.apply?',
      a: 'שניהם מגיעים מ-Function.prototype, קובעים את this כארגומנט ראשון ומריצים את הפונקציה. call מעביר ארגומנטים נוספים בנפרד; apply מעביר אותם כמערך. עם spread, apply פחות נפוץ היום.',
    },
    { code: "greet.call('Puki', 'World')\nMath.max.apply(null, [5, 8, 17, 6])" },
  ),
  card(17, 'JavaScript / Advanced',
    {
      q: 'Challenge: Explain Function.prototype.bind',
      a: 'bind does not execute immediately. It returns a new function with this and initial arguments permanently bound.',
    },
    {
      q: 'אתגר: הסבר את Function.prototype.bind',
      a: 'bind לא מריץ את הפונקציה מיד. הוא מחזיר פונקציה חדשה עם this וארגומנטים ראשוניים קשורים באופן קבוע.',
    },
    { code: "var yaronGreet = greet.bind(null, 'Yaron')\nfunction bind(func, ...args) {\n  return (...moreArgs) => func(...args, ...moreArgs)\n}" },
  ),
  card(18, 'JavaScript / Core',
    {
      q: 'Challenge: What is a higher-order function?',
      a: 'A higher-order function takes a function as an argument or returns a function as its result.',
    },
    {
      q: 'אתגר: מהי higher-order function?',
      a: 'higher-order function מקבלת פונקציה כארגומנט או מחזירה פונקציה כתוצאה.',
    },
    { code: "const arr = [1, 2, 3].map((num) => num + 10)\narr.sort((n1, n2) => n1 - n2)" },
  ),
  card(19, 'JavaScript / Advanced',
    {
      q: 'Challenge: Explain the difference between mutable and immutable objects',
      a: 'Arrays and objects are mutable and can be changed in place. Strings are immutable; methods return new strings. Immutable updates often use spread to create copies.',
    },
    {
      q: 'אתגר: הסבר את ההבדל בין אובייקטים mutable ל-immutable',
      a: 'מערכים ואובייקטים הם mutable וניתן לשנותם במקום. מחרוזות הן immutable; מתודות מחזירות מחרוזות חדשות. עדכונים immutable לעיתים משתמשים ב-spread ליצירת עותקים.',
    },
    { code: "var s = 'papa'\ns[1] = 'u' // s is still papa\nvar pet = { name: 'Charli', score: 90 }\npet = { ...pet, score: 100 }" },
  ),
  card(20, 'JavaScript / ES6+',
    {
      q: 'Challenge: When Immutability is important how do we work with arrays?',
      a: 'reverse(), sort(), and splice() mutate in place. Immutable alternatives include toReversed(), toSorted(), and toSpliced(), which return new arrays.',
    },
    {
      q: 'אתגר: כשחשוב immutability, איך עובדים עם מערכים?',
      a: 'reverse(), sort() ו-splice() משנים במקום. חלופות immutable כוללות toReversed(), toSorted() ו-toSpliced(), שמחזירות מערכים חדשים.',
    },
    { code: "const original = [1, 4]\nconst spliced = original.toSpliced(1, 0, 2, 3)" },
  ),
  card(21, 'JavaScript / Algorithms',
    {
      q: 'Challenge: Implement reduce',
      a: 'reduce loops through items, applies a callback to build an accumulator, and returns a single value. If no initial value is provided, the first item becomes the accumulator.',
    },
    {
      q: 'אתגר: מימוש reduce',
      a: 'reduce עובר על פריטים, מפעיל callback לבניית accumulator ומחזיר ערך יחיד. אם לא סופק ערך התחלתי, הפריט הראשון הופך ל-accumulator.',
    },
    { code: "function myReduce(items, func, accInitialVal) {\n  var acc = accInitialVal !== undefined ? accInitialVal : items[0]\n  var startIdx = accInitialVal !== undefined ? 0 : 1\n  for (let i = startIdx; i < items.length; i++) acc = func(acc, items[i])\n  return acc\n}" },
  ),
  card(22, 'JavaScript / Algorithms',
    {
      q: 'Challenge: Implement Array.deepFlatten',
      a: 'Use recursion with reduce: if an item is an array, flatten it recursively; otherwise push the primitive value.',
    },
    {
      q: 'אתגר: מימוש Array.deepFlatten',
      a: 'השתמשו ברקורסיה עם reduce: אם פריט הוא מערך, שטחו ברקורסיה; אחרת דחפו את הערך הפרימיטיבי.',
    },
    { code: "Array.prototype.deepFlatten = function () {\n  return this.reduce((acc, item) => {\n    if (Array.isArray(item)) acc.push(...item.deepFlatten())\n    else acc.push(item)\n    return acc\n  }, [])\n}" },
  ),
  card(23, 'JavaScript / Core',
    {
      q: 'Challenge: Can you JSON.stringify everything?',
      a: 'No. Circular references throw TypeError. Functions, undefined values, and Symbols are omitted from JSON output.',
    },
    {
      q: 'אתגר: האם ניתן ל-JSON.stringify הכל?',
      a: 'לא. הפניות מעגליות (circular references) זורקות TypeError. functions, ערכי undefined ו-Symbols מושמטים מפלט JSON.',
    },
    { code: "const bobi = { friend: null }\nconst kobi = { friend: bobi }\nbobi.friend = kobi\nJSON.stringify(bobi) // TypeError" },
  ),
  card(24, 'JavaScript / Algorithms',
    {
      q: 'Challenge: What should be the complexity of finding an element in a sorted array?',
      hint: 'Think binary search on a sorted array.',
      a: 'O(log N) using binary search. Linear scan is O(N), but a sorted array allows halving the search space each step.',
    },
    {
      q: 'אתגר: מה צריכה להיות הסיבוכיות של מציאת אלמנט במערך ממוין?',
      hint: 'חשוב על binary search במערך ממוין.',
      a: 'O(log N) באמצעות binary search. סריקה לינארית היא O(N), אך מערך ממוין מאפשר לחצות את מרחב החיפוש בכל שלב.',
    },
  ),
  card(25, 'JavaScript / Algorithms',
    {
      q: 'Challenge: Implement bubble-sort',
      a: 'Bubble sort repeatedly compares adjacent elements and swaps them if out of order. Time complexity is O(N²).',
    },
    {
      q: 'אתגר: מימוש bubble-sort',
      a: 'bubble sort משווה שוב ושוב אלמנטים סמוכים ומחליף אותם אם הם לא בסדר. סיבוכיות זמן: O(N²).',
    },
    { code: "function bubbleSort(a) {\n  var swapped = true\n  while (swapped) {\n    swapped = false\n    for (var i = 0; i < a.length - 1; i++) {\n      if (a[i] > a[i + 1]) { /* swap */ swapped = true }\n    }\n  }\n}" },
  ),
  card(26, 'JavaScript / Algorithms',
    {
      q: 'What should be the complexity of a function that filters duplicates from an array of strings?',
      a: 'O(N) using a Set or a map/object to track seen values, then converting back to an array.',
    },
    {
      q: 'מה צריכה להיות הסיבוכיות של פונקציה שמסננת כפילויות ממערך מחרוזות?',
      a: 'O(N) באמצעות Set או map/object למעקב אחר ערכים שנראו, ואז המרה חזרה למערך.',
    },
    { code: "const votes = ['puk', 'muk', 'shuk', 'muk']\nconst candidates = [...new Set(votes)]" },
  ),
  card(27, 'JavaScript / Algorithms',
    {
      q: "Challenge: Let's Fibonacci",
      a: 'Naive recursion is O(2^n). Memoization reduces it to O(n) by caching previously calculated Fibonacci numbers.',
    },
    {
      q: 'אתגר: Fibonacci',
      a: 'רקורסיה נאיבית היא O(2^n). memoization מפחית ל-O(n) על ידי שמירת מספרי Fibonacci שכבר חושבו ב-cache.',
    },
    { code: "const fiboMap = { '0': 1, '1': 1 }\nfunction getFibonacciNum(idx) {\n  if (idx === 0 || idx === 1) return 1\n  return getFibonacciNum(idx - 1) + getFibonacciNum(idx - 2)\n}" },
  ),
  card(28, 'JavaScript / Async',
    {
      q: 'Challenge: Implement caching',
      a: 'Cache results in an object. On subsequent calls with the same key, return the cached value instead of fetching again.',
    },
    {
      q: 'אתגר: מימוש caching',
      a: 'שמרו תוצאות באובייקט. בקריאות חוזרות עם אותו מפתח, החזירו את הערך מה-cache במקום לבצע fetch מחדש.',
    },
    { code: "const userCache = {}\nasync function getUserDetails(username) {\n  if (userCache[username]) return userCache[username]\n  const user = await fetch(url + username).then(res => res.json())\n  userCache[username] = user\n  return user\n}" },
  ),
  card(29, 'JavaScript / Algorithms',
    {
      q: 'Challenge: Check for balanced parenthesis',
      a: 'Use a stack: push opening brackets, pop and compare on closing brackets. Return true only if all brackets match and the stack is empty.',
    },
    {
      q: 'אתגר: בדיקת סוגריים מאוזנים',
      a: 'השתמשו ב-stack: דחפו סוגריים פותחים, הוציאו והשוו בסוגריים סוגרים. החזירו true רק אם כל הסוגריים תואמים וה-stack ריק.',
    },
    { code: "function isBalancedParanthesis(str) {\n  const stack = []\n  const map = { ')': '(', ']': '[', '}': '{' }\n  // push on open, pop and compare on close\n  return stack.length === 0\n}" },
  ),
  card(30, 'JavaScript / DOM',
    {
      q: 'Challenge: Describe event bubbling',
      a: 'When an event happens on an element, handlers run on it first, then on its parent, and all the way up the ancestor chain. This can be stopped with event.stopPropagation().',
    },
    {
      q: 'אתגר: תאר event bubbling',
      a: 'כשאירוע מתרחש על אלמנט, handlers רצים עליו קודם, ואז על ההורה, ועד שרשרת האבות. ניתן לעצור זאת עם event.stopPropagation().',
    },
  ),
  card(31, 'JavaScript / DOM',
    {
      q: 'Challenge: Describe event delegation',
      a: 'Instead of attaching handlers to every child, attach one handler on a parent and use event.target to handle events from descendants.',
    },
    {
      q: 'אתגר: תאר event delegation',
      a: 'במקום לחבר handlers לכל ילד, חברו handler אחד על ההורה והשתמשו ב-event.target לטיפול באירועים מצאצאים.',
    },
  ),
  card(32, 'JavaScript / DOM',
    {
      q: 'Challenge: display an input and some text, and mark the text according to input',
      a: 'Listen to input events, build a RegExp from the input value, and replace matches in the text with highlighted spans.',
    },
    {
      q: 'אתגר: הצגת input וטקסט, וסימון הטקסט לפי הקלט',
      a: 'האזינו לאירועי input, בנו RegExp מערך הקלט, והחליפו התאמות בטקסט ב-spans מודגשים.',
    },
    { code: "elInput.addEventListener('input', () => {\n  const regex = new RegExp(elInput.value, 'ig')\n  elTxt.innerHTML = elTxt.innerText.replace(regex, m => `<span>${m}</span>`)\n})" },
  ),
  card(33, 'JavaScript / Async',
    {
      q: 'Challenge: Explain synchronous vs. asynchronous functions',
      a: 'Synchronous functions return immediately and block until finished. Asynchronous functions schedule work to run later via callbacks, promises, or timers without blocking the main thread.',
    },
    {
      q: 'אתגר: הסבר פונקציות synchronous לעומת asynchronous',
      a: 'פונקציות synchronous מחזירות מיד וחוסמות עד לסיום. פונקציות asynchronous מתזמנות עבודה להרצה מאוחרת דרך callbacks, promises או timers בלי לחסום את ה-main thread.',
    },
    { code: "function sum(num1, num2) { return num1 + num2 }\nfunction asyncSumWithDelay(num1, num2, cb) {\n  setTimeout(() => cb(num1 + num2), 2500)\n}" },
  ),
  card(34, 'JavaScript / Async',
    {
      q: 'Challenge: Implement an event emitter',
      a: 'Maintain a map of event names to listener arrays. on() registers listeners and returns unsubscribe. emit() calls all listeners for an event.',
    },
    {
      q: 'אתגר: מימוש event emitter',
      a: 'שמרו map של שמות אירועים למערכי listeners. on() רושם listeners ומחזיר unsubscribe. emit() קורא לכל ה-listeners של אירוע.',
    },
    { code: "function createEventEmitter() {\n  const listenersMap = {}\n  return {\n    on(evName, listener) { /* add listener */ },\n    emit(evName, data) { /* call listeners */ }\n  }\n}" },
  ),
  card(35, 'JavaScript / Async',
    {
      q: 'Challenge: Implement promisify',
      a: 'Wrap a callback-style function so it returns a Promise that resolves or rejects based on the callback err/data pattern.',
    },
    {
      q: 'אתגר: מימוש promisify',
      a: 'עטפו פונקציה בסגנון callback כך שתחזיר Promise שמתממש או נדחה לפי דפוס err/data של ה-callback.',
    },
    { code: "function promisify(fn) {\n  return (...args) => new Promise((resolve, reject) => {\n    fn(...args, (err, data) => err ? reject(err) : resolve(data))\n  })\n}" },
  ),
  card(36, 'JavaScript / Async',
    {
      q: 'Challenge: Explain Promises vs. Callbacks',
      a: 'With multiple dependent async steps, Promises produce cleaner code via chaining .then().catch() and utilities like Promise.all().',
    },
    {
      q: 'אתגר: הסבר Promises לעומת Callbacks',
      a: 'עם מספר שלבי async תלויים, Promises מייצרות קוד נקי יותר דרך שרשור .then().catch() וכלי עזר כמו Promise.all().',
    },
    { code: "getData().then(cleanup).then(save).then(renderData).catch(handleErr)" },
  ),
  card(37, 'JavaScript / Async',
    {
      q: 'Challenge: Implement Promise.all',
      a: 'Return a Promise that resolves when all input promises resolve with an array of results, or rejects if any promise rejects.',
    },
    {
      q: 'אתגר: מימוש Promise.all',
      a: 'החזירו Promise שמתממש כשכל ה-promises הקלט מתממשים עם מערך תוצאות, או נדחה אם promise כלשהו נדחה.',
    },
    { code: "function all(promises) {\n  return new Promise((resolve, reject) => {\n    const poolResponses = []\n    promises.forEach((p, idx) => {\n      Promise.resolve(p).then(res => { poolResponses[idx] = res })\n    })\n  })\n}" },
  ),
  card(38, 'JavaScript / Async',
    {
      q: 'Challenge: What is output?\nconsole.log("start")\nsetTimeout(() => console.log("setTimeout"))\nPromise.resolve().then(() => console.log("resolve"))\nconsole.log("end")',
      a: 'Output order: start, end, resolve, setTimeout. Microtasks (Promises) run before macrotasks (setTimeout) after the call stack clears.',
    },
    {
      q: 'אתגר: מה הפלט?\nconsole.log("start")\nsetTimeout(() => console.log("setTimeout"))\nPromise.resolve().then(() => console.log("resolve"))\nconsole.log("end")',
      a: 'סדר הפלט: start, end, resolve, setTimeout. microtasks (Promises) רצות לפני macrotasks (setTimeout) אחרי שה-call stack מתרוקן.',
    },
    { code: "console.log('start')\nsetTimeout(() => console.log('setTimeout'))\nPromise.resolve().then(() => console.log('resolve'))\nconsole.log('end')" },
  ),
  card(39, 'JavaScript / Async',
    {
      q: 'Challenge: What is the event loop',
      a: 'When the call stack is empty, the next callback is removed from the callback queue and pushed to the call stack to be executed by the main thread.',
    },
    {
      q: 'אתגר: מהו event loop',
      a: 'כשה-call stack ריק, ה-callback הבא מוסר מתור ה-callbacks ונדחף ל-call stack להרצה על ידי ה-main thread.',
    },
  ),
  card(40, 'JavaScript / DOM',
    {
      q: 'Challenge: Why would you use something like the load event?',
      a: 'The load event fires when a resource has successfully loaded. It is supported on elements like body, iframe, img, script, and style.',
    },
    {
      q: 'אתגר: למה להשתמש באירוע load?',
      a: 'אירוע load נורה כשמשאב נטען בהצלחה. הוא נתמך באלמנטים כמו body, iframe, img, script ו-style.',
    },
  ),
  card(41, 'JavaScript / Modules',
    {
      q: 'Challenge: How can you share code between files',
      a: 'The modern approach is ES modules with export and import. Older approaches include CommonJS require.',
    },
    {
      q: 'אתגר: איך משתפים קוד בין קבצים',
      a: 'הגישה המודרנית היא ES modules עם export ו-import. גישות ישנות יותר כוללות CommonJS require.',
    },
  ),
];
